version: '3.7'
services:

  #MySQL Service
  db:
    image: ${DOCKER_MYSQL_IMAGE}
    container_name: ${DOCKER_CONTAINER_NAME_SLUG}_db
    restart: unless-stopped
    tty: true
    ports:
      - ${DOCKER_MYSQL_PORTS}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - my-network

#Docker Networks
networks:
  my-network:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
