services:

  #MySQL Service
  docker_db:
    image: ${DB_IMAGE}
    container_name: ${DB_CONTAINER_NAME}
    restart: unless-stopped
    tty: true
    ports:
      - ${DB_PORTS}
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - mynetwork

#Networks: 
networks:
  mynetwork:
    driver: bridge

#Volumes
volumes:
  dbdata:
    driver: local
